# Site settings
title: Will Engler's CS Learning Blog
email: Engler.Will@gmail.com
description: "I learn best by teaching. I will use this blog to teach computer science topics as I learn them at The University of Pittsburgh. I hope you find it useful."
baseurl: ""
url: "http://willengler.github.io"
github_username:  WillEngler

# Build settings
markdown: kramdown
permalink: pretty
