# Dependencies
markdown:         redcarpet
highlighter:		pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hacker In Training
tagline:          'A learning blog'
description:      'Will Engler''s Journey as a Software Apprentice'
url:              http://willengler.github.io
baseurl:          /

author:
  name:           'Will Engler'

paginate:         5

# Custom vars
version:          2.1.0
github_username:	WillEngler

github:
  account:           https://github.com/WillEngler
